accounts/urls.py
from django.urls import path

from userena import views
from .forms import SignupFormExtra

urlpatterns = [
    # Signup form with custom field
    path('signup/', views.signup,
         {'signup_form': SignupFormExtra, 'template_name': 'accounts/signup_form.html'},
         name='userena_signup'),
]

myQuestionnaireSite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('accounts/', include('accounts.urls')),
    path('accounts/', include('userena.urls')),
    path('questionnaire/', include('questionnaire.urls')),
    path('admin/', admin.site.urls),
    path('statistics/', include('questionnaireStatistics.urls')),
]

questionnaire/urls.py
from django.urls import path
from . import views

app_name = 'questionnaire'

urlpatterns = [
    path('', views.Index.as_view(), name='index'),
    path('CreateNewQuestionnaire/', views.Create_Questionnaire.as_view() , name='create'),
    path('<int:questionnaire_id>/delete/', views.Delete_Questionnaire.as_view(), name='delete'),
    path('<int:questionnaire_id>/edit/', views.Edit_Questionnaire.as_view(), name='edit'),
    path('<int:questionnaire_id>/', views.Fill_out_the_questionnaire.as_view(), name='fillOut'),
]

questionnaire/models.py
from django.db import models
from django.contrib.auth.models import User
from accounts.models import MyProfile

# Create your models here.
class Questionnaire(models.Model):
    questionnaire_title = models.CharField(max_length=100)
    questionnaire_description = models.CharField(max_length=200)
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True)

    def __str__(self):
        return self.questionnaire_title

class Question(models.Model):
    question_text = models.CharField(max_length=200)
    questionnaire = models.ForeignKey(Questionnaire, on_delete=models.CASCADE)
    is_mutiple_answers = models.BooleanField()

    def __str__(self):
        return self.question_text

class Choice(models.Model):
    choice_text = models.CharField(max_length=100)
    question = models.ForeignKey(Question, on_delete=models.CASCADE)

    @property
    def counts(self):
        return self.questionnaire_results_set.count()
    
    def __str__(self):
        return self.choice_text

class Questionnaire_Results(models.Model):
    GENDER_CHOICES = MyProfile.GENDER_CHOICES
    ANNUAL_INCOME_CHOICES = MyProfile.ANNUAL_INCOME_CHOICES
    EDUCATION_CHOICES = MyProfile.EDUCATION_CHOICES

    questionnaire = models.ForeignKey(Questionnaire, on_delete=models.CASCADE)
    gender = models.CharField(max_length=10, choices=GENDER_CHOICES)
    birthday = models.DateField()
    education = models.CharField(max_length=1, choices=EDUCATION_CHOICES)
    annual_income = models.IntegerField(choices=ANNUAL_INCOME_CHOICES)
    choice = models.ManyToManyField(Choice)
    fill_time = models.DateTimeField(auto_now_add=True)

questionnaire/forms.py
from django import forms
from .models import Questionnaire_Results

class Results_form(forms.Form):
    gender = forms.ChoiceField(choices=Questionnaire_Results.GENDER_CHOICES, widget=forms.RadioSelect)

questionnaire/views.py
from django.shortcuts import render, get_object_or_404
from django.views.generic import View
from django.contrib.auth.mixins import LoginRequiredMixin
from .models import Questionnaire, Question, Choice, Questionnaire_Results
from .forms import Results_form

# Create your views here.
class Index(View):
    def get(self, request):
        questionnaires = None
        if request.user.is_authenticated:
            questionnaires = Questionnaire.objects.filter(user=request.user)
        return render(request, 'questionnaire/index.html',
                    {'questionnaire_list': questionnaires})

class Create_Questionnaire(LoginRequiredMixin, View):
    def get(self, request):
        return render(request, 'questionnaire/create.html')

    def post(self, request):
        questionnaire = Questionnaire()
        questionnaire.questionnaire_title = request.POST['questionnaire_title']
        questionnaire.questionnaire_description = request.POST['questionnaire_description']
        questionnaire.user = request.user
        questionnaire.save()
        for key in request.POST.keys():
            key_split = key.split('_')
            if 'question' in key_split:
                if 'choice' in key_split:
                    choice = Choice()
                    choice.choice_text = request.POST[key]
                    choice.question = question
                    choice.save()
                elif key.endswith('allowed_mutiple_answers'):
                    question.is_mutiple_answers = True
                    question.save()
                else:
                    question = Question()
                    question.question_text = request.POST[key]
                    question.questionnaire = questionnaire
                    question.is_mutiple_answers = False
                    question.save()
        return render(request, 'questionnaire/create.html')

class Delete_Questionnaire(LoginRequiredMixin, View):
    succeed = False
    def get(self, request, questionnaire_id):
        qeustionnaire = get_object_or_404(Questionnaire, pk=questionnaire_id, user=request.user)
        return render(request, 'questionnaire/delete.html',
                      {'questionnaire': qeustionnaire, 'delete_succeed': self.succeed})

    def post(self, request, questionnaire_id):
        qeustionnaire = get_object_or_404(Questionnaire, pk=questionnaire_id, user=request.user)
        qeustionnaire.delete()
        self.succeed = True
        return render(request, 'questionnaire/delete.html',
                      {'delete_succeed': self.succeed})

class Edit_Questionnaire(LoginRequiredMixin, View):
    is_updated = False
    def get(self, request, questionnaire_id):
        qeustionnaire = get_object_or_404(Questionnaire, pk=questionnaire_id, user=request.user)
        return render(request, 'questionnaire/edit.html',
                      {'questionnaire': qeustionnaire})

    def post(self, request, questionnaire_id):
        questionnaire = get_object_or_404(Questionnaire, pk=questionnaire_id, user=request.user)
        questionnaire.questionnaire_title = request.POST['questionnaire_title']
        questionnaire.questionnaire_description = request.POST['questionnaire_description']
        questionnaire.save()
        keys = request.POST.keys()

        for key in keys:
            key_set = key.split('_')
            if 'question' in key_set:
                question_id = int(key_set[-2])
                try:
                    question = Question.objects.get(pk=question_id)
                    if key_set[0] == 'delete':
                        question.delete()
                    else:
                        question.question_text = request.POST[key]
                        if str(question_id)+'_allowed_mutiple_answers' in keys:
                            question.is_mutiple_answers = True
                        else:
                            question.is_mutiple_answers = False
                        question.save()
                except question.DoesNotExist:
                    print('Question {} does not exist.'.format(question_id))
            elif 'choice' in key_set:
                choice_id = int(key_set[-2])
                try:
                    choice = Choice.objects.get(pk=choice_id)
                    if key_set[0] == 'delete':
                        choice.delete()
                    else:
                        choice.choice_text = request.POST[key]
                        choice.save()
                except choice.DoesNotExist:
                    print('choice {} does not exist.'.format(choice_id))
        self.is_updated = True
        return render(request, 'questionnaire/edit.html',
                      {'questionnaire': questionnaire, 'is_updated': self.is_updated})

class Fill_out_the_questionnaire(View):
    def get(self, request, questionnaire_id):
        qeustionnaire = get_object_or_404(Questionnaire, pk=questionnaire_id)
        questionnaire_results = Questionnaire_Results()
        return render(request, 'questionnaire/fillOut.html',
                      {'questionnaire': qeustionnaire,
                       'questionnaire_results': questionnaire_results})
    
    def post(self, request, questionnaire_id):
        questionnaire = get_object_or_404(Questionnaire, pk=questionnaire_id)
        questionnaire_results = Questionnaire_Results()
        questionnaire_results.questionnaire = questionnaire
        questionnaire_results.birthday = request.POST['birthday']
        questionnaire_results.gender = request.POST['gender']
        questionnaire_results.education = request.POST['education']
        questionnaire_results.annual_income = request.POST['annual_income']
        questionnaire_results.save()
        for key in request.POST.keys():
            if 'choice' in key:
                choice = Choice.objects.get(pk=request.POST.get(key))
                questionnaire_results.choice.add(choice)
        questionnaire_results.save()
        return render(request, 'questionnaire/fillOut.html',
                      {'questionnaire': questionnaire,
                       'questionnaire_results': questionnaire_results})

questionnaire/templates/questionnaire/base.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Base</title>
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <link rel="stylesheet" href="https://ajax.googleapis.com/ajax/libs/jqueryui/1.12.1/themes/smoothness/jquery-ui.css">
  </head>
  <body>
    <nav class="navbar navbar-default navbar-static-top">
      <div class="container">
        <ul class="nav navbar-nav">
          {# Django Home Link / Admin Link / Register Link#}
          <li><a class="navbar-brand" href="{% url 'questionnaire:index' %}">myQuestionnaire</a></li>
          <li><a class="navbar-link" href="{% url 'admin:index' %}">管理者登入</a></li>     
          {# Some logic on what to display for last item#}
          {% if user.is_authenticated %}
            <li><a href="{% url 'member:logout' %}">登出</a></li>
          {% else %}
            <li><a class="navbar-link" href="{% url 'member:register' %}">註冊</a></li>
            <li><a class="navbar-link" href="{% url 'member:user_login' %}">登入</a></li>
          {% endif %}
        </ul>
      </div>
    </nav>
    <div class="container">
    {% block body_block %}
    {% endblock %}
    </div>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.js"></script>
    {% block script_block %}
    {% endblock %}
  </body>
</html>

questionnaire/templates/questionnaire/create.html
{% extends "base.html" %}
{% block body_block %}
<form method="POST" action="{% url 'questionnaire:create' %}" class="form-horizontal">
    {% csrf_token %}
    <div class="form-group">
        <label for="id_questionnaire_title" class="col-sm-2 control-label">問卷標題：</label>
        <div class="col-sm-10">
            <input type="text" required name="questionnaire_title" id="id_questionnaire_title" class="form-control">
        </div>
    </div>
    <div class="form-group">
        <label for="id_questionnaire_description" class="control-label col-sm-2">問卷說明：</label>
        <div class="col-sm-10">
            <input type="text" required name="questionnaire_description" id="id_questionnaire_description" class="form-control">
        </div>
    </div>
    <div class="form-group" id="question_1">
        <div class="col-sm-offset-2 col-sm-10">
            <div class="panel panel-default">
                <div class="panel-heading">問題1</div>
                <div class="panel-body">
                    <div class="form-group">
                        <label for="id_question_1_text" class="control-label col-sm-2">問題內容</label>
                        <div class="col-sm-8">
                            <input type="text" required name="question_1_text" id="id_question_1_text" class="form-control">
                        </div>
                        <div class="checkbox col-sm-2">
                            <label for="id_question_1_allowed_mutiple_answers"><input type="checkbox" name="question_1_allowed_mutiple_answers" id="id_question_1_allowed_mutiple_answers">是否允許多選</label> 
                        </div>
                    </div>
                    <div class="form-group" id="group_question_1_choice_text_1">
                        <label for="id_question_1_choice_text_1" class="control-label col-sm-2">選項1</label>
                        <div class="col-sm-10">
                            <input type="text" required name="question_1_choice_text_1" id="id_question_1_choice_text_1" class="form-control">
                        </div>
                        <div class="col-sm-offset-2 col-sm-10">
                            <button type="button" onclick="addChoice(this)" value="question_1_choice_text_1"  class="btn btn-success">新增選項</button>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <button type="button" value="question_1" onclick="addQuestion(this)" class="btn btn-info">新增問題</button>
            <button type="submit" class="btn btn-primary">確認送出</button>
        </div>
    </div>
</form>
{% endblock %}
{% block script_block %}
{% load static %}
<script src="{% static 'js/createQuestionnaire.js' %}"></script>
{% endblock %}

questionnaire/templates/questionnaire/delete.html
{% extends 'questionnaire/base.html' %}
{% block body_block %}
    {% if delete_succeed %}
    <div class="page-header">
        <h1>問卷已刪除。</h1>
    </div>
    {% else %}
    <div class="page-header">
        <h1>刪除問卷會一併刪除問卷結果，你確定要刪除此問卷?</h1>
    </div>
    <div class="row">
        <div class="col-sm-10">
            <p>問卷標題： {{ questionnaire.questionnaire_title }}</p>
        </div>
    </div>
    <div class="row">
        <div class="col-sm-10">
            <p>問卷說明： {{ questionnaire.questionnaire_description }}</p>
        </div>
    </div>
    <form action="" method="post">
        {% csrf_token %}
        <button class="btn btn-danger" type="submit">確定</button>
        <a href="{% url 'questionnaire:index' %}" class="btn btn-default" role="button">取消</a>
    </form>
    {% endif %}
{% endblock %}

questionnaire/templates/questionnaire/edit.html
{% extends 'base.html' %}
{% block css%}
{% load static %}
<link rel="stylesheet" href="{% static 'css/style.css' %}">
{% endblock %}
{% block body_block %}
{% if is_updated %}
    <div class="page-header"><h1>問卷內容已更新。</h1></div>
{% endif %}
    <form action="" method="post" class="form-horizontal">
        {% csrf_token %}
        <div class="form-group">
            <label for="questionnaire_title" class="col-sm-2 control-label">問卷標題：</label>
            <div class="col-sm-10">
                <input type="text" name="questionnaire_title" value="{{ questionnaire.questionnaire_title }}" id="questionnaire_title" class="form-control">
            </div>
        </div>
        <div class="form-group">
            <label for="questionnaire_description" class="col-sm-2 control-label">問卷說明：</label>
            <div class="col-sm-10">
                <input type="text" name="questionnaire_description" value="{{ questionnaire.questionnaire_description }}" id="questionnaire_description" class="form-control">
            </div>
        </div>
        {% for question in questionnaire.question_set.all %}
        <div class="form-group" id="question_{{ question.id }}">
            <div class="col-sm-offset-2 col-sm-10">
                <div class="panel panel-default">
                    <div class="panel-heading">問題 {{ forloop.counter }}</div>
                    <div class="panel-body">
                        <div class="form-group">
                            <label for="question_{{ question.id }}_text" class="control-label col-sm-2">問題內容：</label>
                            <div class="col-sm-8">
                                <input type="text" name="question_{{ question.id }}_text" id="question_{{ question.id }}_text" value="{{ question.question_text }}" class="form-control">
                            </div>
                            <div class="col-sm-1">
                                <button type="button" value="question_{{ question.id }}_delete" onclick="deleteElement(this)" class="btn btn-danger">刪除問題</button>
                            </div>
                            <div class="col-sm-offset-2 col-sm-6 checkbox">
                                <label for="{{ question.id }}_allowed_mutiple_answers"><input type="checkbox" name="{{ question.id }}_allowed_mutiple_answers" id="{{ question.id }}_allowed_mutiple_answers" {%if question.is_mutiple_answers %}checked{% endif %}>是否允許多選</label>
                            </div>
                        </div>
                        {% for choice in question.choice_set.all %}
                        <div class="form-group" id="choice_{{ choice.id }}">
                            <label for="choice_{{ choice.id }}_text" class="control-label col-sm-2">選項 {{ forloop.counter }}：</label>
                            <div class="col-sm-8">
                                <input type="text" name="choice_{{ choice.id }}_text" id="choice_{{ choice.id }}_text" value="{{ choice.choice_text }}" class="form-control">
                            </div>
                            <div class="col-sm-1">
                                <button type="button" value="choice_{{ choice.id }}_delete" onclick="deleteElement(this)" class="btn btn-warning btn-sm">刪除選項</button>
                            </div>
                        </div>
                        {% endfor %}
                    </div>
                </div>
            </div>
        </div>
        {% endfor %}
        <div class="form-group">
            <div class="col-sm-offset-2 col-sm-1">
                <button type="submit" class="btn btn-primary">確認修改</button>
            </div>
            <div class="col-sm-1">
                <a href="{% url 'questionnaire:index' %}" class="btn btn-default" role="button">回問卷清單</a>
            </div>
        </div>
    </form>
{% endblock %}
{% block script_block %}
{% load static %}
<script src="{% static 'js/editQuestionnaire.js' %}"></script>
{% endblock %}

questionnaire/templates/questionnaire/fillOut.html
{% extends 'base.html' %}
{% load static %}
{% block css %}
<link rel="stylesheet" href="{% static 'css/style.css' %}">
{% endblock %}
{% block body_block %}
<div>
    <p>問卷標題：{{ questionnaire.questionnaire_title }}</p>
    <p>問卷說明：{{ questionnaire.questionnaire_description }}</p>
</div>
<form action="" method="post" class="form-horizontal">
    {% csrf_token %}
    <div class="panel panel-info">
        <div class="panel-heading">基本資料</div>
        <div class="panel-body">
            <div class="form-group">
                <label class="control-label col-sm-1" for="id_birthday">生日</label>
                <div class="col-sm-2">
                    <input type="text" name="birthday" required id="id_birthday" class="form-control" readonly>
                </div>
            </div>
            <div class="form-group">
                <label for="gender" class="col-sm-1 control-label">性別</label>
                <div class="col-sm-2">
                    <select name="gender" id="gender" class="form-control" required>
                        <option>請選擇</option>
                    {% for value, text in questionnaire_results.GENDER_CHOICES %}
                        <option value="{{ value }}">{{ text }}</option>
                    {% endfor %}
                    </select>
                </div>
            </div>
            <div class="form-group">
                <label for="education" class="col-sm-1 control-label">學歷</label>
                <div class="col-sm-2">
                    <select name="education" id="education" class="form-control">
                        <option>請選擇</option>
                    {% for value, text in questionnaire_results.EDUCATION_CHOICES %}
                        <option value="{{ value }}">{{ text }}</option>
                    {% endfor %}
                    </select>
                </div>
            </div>
            <div class="form-group">
                <label for="annual_income" class="required col-sm-1 control-label">年收入</label>
                <div class="col-sm-2">
                    <select name="annual_income" id="annual_income" class="form-control">
                        <option>請選擇</option>
                    {% for value, text in questionnaire_results.ANNUAL_INCOME_CHOICES %}
                        <option value="{{ value }}">{{ text }}</option>
                    {% endfor %}
                    </select>
                </div>
            </div>
        </div>
    </div>
    {% for question in questionnaire.question_set.all %}
    <ul class="list-group">
        <li class="list-group-item active"><label>問題 {{ forloop.counter }}: {{ question.question_text }}</label></li>
        {% for choice in question.choice_set.all %}
        {% if question.is_mutiple_answers %}
        <li class="list-group-item"><input type="checkbox" name="choice-{{ choice.id }}" id="choice-{{ choice.id }}" value="{{ choice.id }}"><label for="choice-{{ choice.id }}">{{ choice.choice_text }}</label></li>
        {% else %}
        <li class="list-group-item"><input type="radio" name="question-{{ question.id }}-choice" id="choice-{{ choice.id }}" value="{{ choice.id }}"><label for="choice-{{ choice.id }}">{{ choice.choice_text }}</label></li>
        {% endif %}
        {% endfor %}
    </ul>
    {% endfor %}
    <div class="form-group">
        <button type="submit" class="btn btn-success">確認送出</button>
    </div>
</form>
{% endblock %}
{% block script_block %}
<script src="{% static 'js/fillOutFormValidation.js' %}"></script>
{% endblock %}

questionnaire/templates/questionnaire/index.html
{% extends 'base.html' %}
{% block body_block %}
{% if user.is_authenticated %}
    {% if questionnaire_list %}
        {% for questionnaire in questionnaire_list %}
        <div class="panel panel-primary">
            <div class="panel-heading">{{ forloop.counter }}. {{ questionnaire.questionnaire_title }}</div>
            <div class="panel-body">
                <div class="row">
                    <div class="col-sm-12">{{ questionnaire.questionnaire_description }}</div>
                </div>
                <div class="row">    
                    <div class="col-sm-1">
                        <a href="{% url 'questionnaire:edit' questionnaire.id %}" class="btn btn-info" role="button">修改</a>
                    </div>
                    <div class="col-sm-1">
                        <a href="{% url 'questionnaire:delete' questionnaire.id %}" class="btn btn-warning" role="button">刪除</a>
                    </div>
                </div>
            </div>
        </div>
        {% endfor %}
    {% else %}
        <p>尚未新增任何問卷</p>
    {% endif %}
    <a href="{% url 'questionnaire:create' %}" class="btn btn-lg btn-primary" role="button">按此新增問卷</a>
{% else %}
    <div class="page-header">
        <h2>請先登入</h2>
    </div>
    <p><a href="{% url 'userena_signin' %}" class="btn btn-default" role="button">登入</a></p>
{% endif %}
{% endblock %}